---
- name: Dowload zabbix repo
  get_url: url="https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu20.04_all.deb" dest=/home/vagrant

- name: Install zabbix deb
  command: dpkg -i /home/vagrant/zabbix-release_6.0-4+ubuntu20.04_all.deb

- name: Update packeges
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: Install Zabbix server, frontend, agent
  apt: pkg={{ item }} state=present
  become: true
  with_items:
    - zabbix-server-pgsql
    - zabbix-frontend-php
    - php7.4-pgsql
    - zabbix-apache-conf
    - zabbix-sql-scripts
    - zabbix-agent

- name: Install postrges 
  apt: pkg={{ item }} state=present
  become: true
  with_items:
    - postgresql
    - postgresql-contrib
    - python3-pip
    - python3-dev
    - python3-venv
    - python3-psycopg2

- name: Configure postgres pg_hba.conf
  become: true
  template:
    src: "pg_hba.conf"
    dest: "/etc/postgresql/12/main/"
    mode: 0644

- name: Configure postgres postrgesql.conf
  lineinfile:
    path: /etc/postgresql/12/main/postgresql.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^# listen_addresses = 'localhost'", line: "listen_addresses = '*'" }

- name: Ensure the PostgreSQL service is running 
  service: 
    name: postgresql
    state: started 
    enabled: yes

- name: Create DB user
  become: true
  become_user: postgres
  postgresql_user:
    state: present
    login_user: postgres
    login_password: postgres
    name: zabbix
    password: password
    role_attr_flags: SUPERUSER

- name: Create zabbix DB
  become: true
  become_user: postgres
  postgresql_db:
    login_user: postgres
    login_password: postgres
    name: zabbix
    state: present

- name: Prepare public schema
  shell: zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz > /home/vagrant/server.sql

- name: Import schema
  become: true
  become_user: postgres
  postgresql_db:
    login_user: postgres
    login_password: postgres
    name: zabbix
    state: restore
    target: /home/vagrant/server.sql

- name: Set zabbix configuration variables
  lineinfile:
    path: /etc/zabbix/zabbix_server.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^DBHost=', line: 'DBHost=localhost' }
    - { regexp: '^DBName=', line: 'DBName=zabbix' }
    - { regexp: '^DBUser=', line: 'DBUser=zabbix' }
    - { regexp: '^DBPassword', line: 'DBPassword=password' } 

- name: Configure Apache for Zabbix
  template:
    src: "php.ini"
    dest: "/etc/php/7.4/apache2/"
    mode: 0644

#- name: Configure PHP for Zabbix frontend
#  lineinfile:
#    path: /etc/zabbix/nginx.conf
#    regexp: "{{ item.regexp }}"
#    line: "{{ item.line }}"
#  with_items:
#    - { regexp: '^# listen 8080;', line: 'listen 8080;' }
#    - { regexp: '^# server_name example.com;', line: 'server_name zabbix.com;' }

- name: Restart servises
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - zabbix-server
    - zabbix-agent
    - apache2
  

