---
- name: Download Zabbix repo
  get_url: url="{{ zabbix_server_version_deb }}" dest=/home/vagrant

- name: Install Zabbix deb
  apt: deb=/home/vagrant/zabbix-release_latest+ubuntu20.04_all.deb

- name: Install zabbix server
  apt:
    name:
      "zabbix-server-{{ zabbix_database_type }}"

- name: Install zabbix frontend
  apt:
    name:
      "zabbix-frontend-php"

- name: Install MySQL packages
  apt: pkg={{ item }} state=present
  become: true
  with_items:
    - bundler
    - mysql-server
    - mysql-client
    - libmysqlclient-dev
    - python3-mysqldb
    - build-essential


- name: Update mysql root password
  mysql_user: 
    login_user: root
    login_password: "{{ zabbix_database_password }}" 
    name: root 
    password: "{{ zabbix_database_password }}" 
    priv: "*.*:ALL,GRANT"

- name: Configure zabbix database
  mysql_db:
    login_user: root
    login_password: "{{ zabbix_database_password }}"
    name: "{{ zabbix_database_name }}"
    state: present

- name: Prepare schema
  shell: zcat /usr/share/zabbix-server-mysql/schema.sql.gz > /usr/share/zabbix-server-mysql/schema.sql

- name: Import schema
  mysql_db:
    login_user: root
    login_password: "{{ zabbix_database_password }}"
    name: "{{ zabbix_database_name }}"
    state: import
    target: /usr/share/zabbix-server-mysql/schema.sql

- name: Create zabbix database user
  mysql_user:
    login_user: root
    login_password: "{{ zabbix_database_password }}"
    name: "{{ zabbix_database_user }}"
    host: "{{ zabbix_database_host }}"
    password: "{{ zabbix_database_password }}"
    priv: "{{ zabbix_database_name }}.*:ALL"
    state: present

- name: Set zabbix configuration variables
  lineinfile:
    path: /etc/zabbix/zabbix_server.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^DBHost=', line: 'DBHost={{ zabbix_database_host }}' }
    - { regexp: '^DBPort=', line: 'DBPort={{ zabbix_database_port }}' }
    - { regexp: '^DBName=', line: 'DBName={{ zabbix_database_name }}' }
    - { regexp: '^DBUser=', line: 'DBUser={{ zabbix_database_user }}' }
    - { regexp: '^DBPassword', line: 'DBPassword={{ zabbix_database_password }}' }
    - { regexp: '^StartPollers=', line: 'StartPollers=20' }
    - { regexp: '^StartPollersUnreachable=', line: 'StartPollersUnreachable=10' }