---
- name: Install Zabbix-agent service 
  become: true
  opkg:
    name: zabbix-agentd
    state: present
    update_cache: yes


- name: Configure Zabbix Agent
  become: true
  lineinfile:
    path: "/etc/zabbix_agentd.conf"
    line: "{{ item }}"
  with_items: 
    - "Server={{ ip_zabbix_server }}"
    - "Hostname={{ inventory_hostname }}"
    - "ServerActive={{ ip_zabbix_server }}"

- name: Restart Zabbix-agent 
  service:
    name: zabbix_agentd
    state: restarted