---
- name: Update packadge
  become: true
  apt: 
    upgrade: yes
    update_cache: yes 

- name: Install Zabbix-agent service 
  become: true
  apt:
    name: zabbix-agent
    state: present

- name: Configure Zabbix Agent
  become: true
  lineinfile:
    path: "/etc/zabbix/zabbix_agentd.conf"
    line: "{{ item }}"
  with_items: 
    - "Server={{ ip_zabbix_server }}"
    - "Hostname={{ inventory_hostname }}"
    - "ServerActive={{ ip_zabbix_server }}"
  notify: restart zabbix agent service