---
- name: Update packeges
  become: true
  apt: 
    upgrade: yes
    update_cache: yes

- name: Add the repository that provides PostgreSQL 14
  shell: sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

- name: Import the GPG signing key
  shell: wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

- name: Install packeges
  apt: pkg={{ item }} state=present
  become: true
  with_items:
    - apt-transport-https 
    - wget 
    - gnupg

- name: Install Repo
  shell: wget -O - https://packages.icinga.com/icinga.key | gpg --dearmor -o /usr/share/keyrings/icinga-archive-keyring.gpg; . /etc/os-release; if [ ! -z ${UBUNTU_CODENAME+x} ]; then DIST="${UBUNTU_CODENAME}"; else DIST="$(lsb_release -c| awk '{print $2}')"; fi; \ echo "deb [signed-by=/usr/share/keyrings/icinga-archive-keyring.gpg] https://packages.icinga.com/ubuntu icinga-${DIST} main" > \ /etc/apt/sources.list.d/${DIST}-icinga.list echo "deb-src [signed-by=/usr/share/keyrings/icinga-archive-keyring.gpg] https://packages.icinga.com/ubuntu icinga-${DIST} main" >> \ /etc/apt/sources.list.d/${DIST}-icinga.list

- name: Update pack
  become: true
  apt: 
    upgrade: yes
    update_cache: yes
  
- name: Install Icinga2
  become: true
  apt: 
    name: ['icinga2', 'monitoring-plugins']
    state: present

- name: Start Icinga2 Deamon
  shell: icinga2 daemon -C

- name: Install postrges 
  apt: pkg={{ item }} state=present
  become: true
  with_items:
    - postgresql-14
    - postgresql-contrib
    - python3-pip
    - python3-dev
    - python3-venv
    - python3-psycopg2
    - icinga2-ido-pgsql

- name: Install Icinga2 web
  apt: pkg={{ item }} state=present
  become: true
  with_items: 
    - icingaweb2
    - libapache2-mod-php
    - icingacli

- name: Install the web server
  shell: icingacli setup config webserver apache --document-root /usr/share/icingaweb2/public

- name: Configure postgres pg_hba.conf
  become: true
  template:
    src: "pg_hba.conf"
    dest: "/etc/postgresql/14/main/"
    mode: 0644
  
- name: Configure postgres postrgesql.conf
  lineinfile:
    path: /etc/postgresql/14/main/postgresql.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^# listen_addresses = 'localhost'", line: "listen_addresses = '*'" }

- name: Ensure the PostgreSQL service is running 
  service: 
    name: postgresql
    state: started 
    enabled: yes

- name: Create DB user
  become: true
  become_user: postgres
  postgresql_user:
    state: present
    login_user: postgres
    login_password: postgres
    name: icinga
    password: password
    role_attr_flags: SUPERUSER

- name: Create icinga DB
  become: true
  become_user: postgres
  postgresql_db:
    login_user: postgres
    login_password: postgres
    name: icinga
    state: present

- name: Import schema
  become: true
  become_user: postgres
  postgresql_db:
    login_user: postgres
    login_password: postgres
    name: icinga
    state: restore
    target: /usr/share/icinga2-ido-pgsql/schema/pgsql.sql

- name: Enable ido-pgsql features
  shell: icinga2 feature enable ido-pgsql

- name: Restart servises
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - postgresql
    - icinga2
    - apache2
  